version: '2.1'
services:
  cassandra:
    image: cassandra-local:latest
    build: ./cassandra-datastore
    container_name: cassandra
    command: "sh /init.sh"
    ports:
    - "127.0.0.1:9042:9042"